platform :ios, '8.0'

inhibit_all_warnings!

#use_frameworks!

workspace 'Example/PEPNetworking.xcworkspace'


target 'PEPNetworking_Example' do
  pod 'PEPNetworking', :path => '../'
  
#  pod 'PEPBigData', :git => 'https://github.com/PEPDigitalPublishing/PEPBigData.git'

  target 'PEPNetworking_Tests' do
    inherit! :search_paths

  end
  
end

target 'PEPNetworking' do
  project 'Pods/Pods.xcodeproj'
  
  pod 'AFNetworking'
  
  pod 'PEPBigData', :git => 'https://github.com/PEPDigitalPublishing/PEPBigData.git'

end
